/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Raul
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setTitle("CONTROLE CLINICA MÉDICA");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }
    
    private void abrirFormulario(JInternalFrame f) {
        if (areaTrabalho.getAllFrames().length == 0) {
            areaTrabalho.add(f);
            Dimension d = f.getDesktopPane().getSize();
            f.setLocation(
                (d.width - f.getSize().width) / 2,
                (d.height - f.getSize().height) / 2
            );
            f.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuItemCadastrarMedico = new javax.swing.JMenuItem();
        menuItemCadastrarPaciente = new javax.swing.JMenuItem();
        menuItemCadastrarEspecialidade = new javax.swing.JMenuItem();
        menuVisualizar = new javax.swing.JMenu();
        menuItemVisualizarMedico = new javax.swing.JMenuItem();
        menuItemVisualizarPaciente = new javax.swing.JMenuItem();
        menuItemVisualizarEspecialidade = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuItemConsultasAgendamento = new javax.swing.JMenuItem();
        menuItemConsultasVisualizar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");

        menuItemCadastrarMedico.setText("Medico");
        menuItemCadastrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarMedicoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastrarMedico);

        menuItemCadastrarPaciente.setText("Paciente");
        menuItemCadastrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarPacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastrarPaciente);

        menuItemCadastrarEspecialidade.setText("Especialidade");
        menuItemCadastrarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarEspecialidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastrarEspecialidade);

        barraMenu.add(menuCadastro);

        menuVisualizar.setText("Visualizar");

        menuItemVisualizarMedico.setText("Medico");
        menuItemVisualizarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarMedicoActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarMedico);

        menuItemVisualizarPaciente.setText("Paciente");
        menuItemVisualizarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarPacienteActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarPaciente);

        menuItemVisualizarEspecialidade.setText("Especialidade");
        menuItemVisualizarEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVisualizarEspecialidadeActionPerformed(evt);
            }
        });
        menuVisualizar.add(menuItemVisualizarEspecialidade);

        barraMenu.add(menuVisualizar);

        menuConsultas.setText("Consultas");

        menuItemConsultasAgendamento.setText("Agendamento");
        menuItemConsultasAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultasAgendamentoActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemConsultasAgendamento);

        menuItemConsultasVisualizar.setText("Visualizar");
        menuItemConsultasVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultasVisualizarActionPerformed(evt);
            }
        });
        menuConsultas.add(menuItemConsultasVisualizar);

        barraMenu.add(menuConsultas);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCadastrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarPacienteActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormCadastroPaciente());
    }//GEN-LAST:event_menuItemCadastrarPacienteActionPerformed

    private void menuItemVisualizarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarMedicoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormPesquisaMedico());
    }//GEN-LAST:event_menuItemVisualizarMedicoActionPerformed

    private void menuItemVisualizarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarPacienteActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormPesquisaPaciente());
    }//GEN-LAST:event_menuItemVisualizarPacienteActionPerformed

    private void menuItemConsultasVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultasVisualizarActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormPesquisaConsulta());
    }//GEN-LAST:event_menuItemConsultasVisualizarActionPerformed

    private void menuItemCadastrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarMedicoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormCadastroMedico());
    }//GEN-LAST:event_menuItemCadastrarMedicoActionPerformed

    private void menuItemCadastrarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarEspecialidadeActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormCadastroEspecialidade());
    }//GEN-LAST:event_menuItemCadastrarEspecialidadeActionPerformed

    private void menuItemConsultasAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultasAgendamentoActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormAgendamentoConsulta());
    }//GEN-LAST:event_menuItemConsultasAgendamentoActionPerformed

    private void menuItemVisualizarEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVisualizarEspecialidadeActionPerformed
        // TODO add your handling code here:
        abrirFormulario(new FormPesquisaEspecialidade());
    }//GEN-LAST:event_menuItemVisualizarEspecialidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenuItem menuItemCadastrarEspecialidade;
    private javax.swing.JMenuItem menuItemCadastrarMedico;
    private javax.swing.JMenuItem menuItemCadastrarPaciente;
    private javax.swing.JMenuItem menuItemConsultasAgendamento;
    private javax.swing.JMenuItem menuItemConsultasVisualizar;
    private javax.swing.JMenuItem menuItemVisualizarEspecialidade;
    private javax.swing.JMenuItem menuItemVisualizarMedico;
    private javax.swing.JMenuItem menuItemVisualizarPaciente;
    private javax.swing.JMenu menuVisualizar;
    // End of variables declaration//GEN-END:variables
}
